### ISSUE TITLE
 Problem with default filled fields

### ISSUE THREAD

**Issue by adambichler** [erikyo/cf7-antispam#10]
Hello,

The plugin seems to work just fine, however I think I found a minor bug:

When using a contact form 7 input field with the value default:user_first_name (for example), the hidden honeypot field also seems to inherit that same value, resulting in the form not beeing able to be sent.

When using the cf7 field without the default value, everything is working as expected.

Let me know if you need any further explaination on the bug.
Would be nice to resolve that bug, as it is neccessary on my site.

Thanks for the amazing work on the plugin!

Adam

**Comment by erikyo** [comment]
@adambichler thanks 💯 for your report! 

The honeypots in this plugin are created automatically by duplicating the inputs and in this case the contents of the field are not emptied properly.

This is the case that triggers the issue:
`[text text-123" default"]`

Thanks again, I am preparing a new version that I will release in the next few days, I will also include this fix

**Comment by adambichler** [comment]
@erikyo I thought so! Thanks for the quick response, I'm looking forward to the fix!

Thanks, Adam

**Comment by erikyo** [comment]
In addition, I've also [fixed an issue that happened when the honeypots](https://github.com/erikyo/cf7-antispam/commit/0e3fa8637727491b32e3099004df116a4d669e9b) are enabled and they were inside an invalid html block (or something that php DOMdocument doesn't recognise as valid). A wordpress forum user had pointed [out to me](https://wordpress.org/support/topic/it-breaks-the-my-custom-form-template/) some time ago but I did not understand how to reproduce the issue

**Comment by adambichler** [comment]
Thank you!

**Comment by adambichler** [comment]
@erikyo 
I can confirm that in the current beta version 0.4.0, this issue is fixed. Thanks!
