### ISSUE TITLE
Plugin not PHP 8.x compatible

### ISSUE THREAD

**Issue by nosajimiki** [erikyo/cf7-antispam#31]
I recently tried updating our server from PHP 7.4 to PHP 8.1, and this plugin causes the a fatal error shown below. 

![image](https://user-images.githubusercontent.com/123778558/215214282-b3e0b891-f2da-458e-b0f6-7a972b4cae2f.png)

**Comment by erikyo** [comment]
Thanks @nosajimiki for the report, I will try to release soon a version that fixes this problem.

**Comment by Mte90** [comment]
Doesn't seems a PHP8 issue the function exists since php 4 https://www.php.net/manual/en/function.mb-convert-encoding.php

It seems more a missing php-mbstring package in the machine. You need to enable or install that module.

**Comment by nosajimiki** [comment]
That was the problem, looks like EasyApache does not provision php81-php-mbstring by default.  Thanks.
