### ISSUE TITLE
Feature Request: Please add an exception list (page ids) to new Honeyform functionality

### ISSUE THREAD

**Issue by linuxlurak** [erikyo/cf7-antispam#40]
First of all: Thank you for this wonderful plugin and your time you invested in this project!

I tested the honeyform functionality of your plugin and it would be nice to have the possibility to define a list of pages where your plugin won't insert the honeyform. 

Use case: I'm sending an automatically generated wordpress website as a html newsletter and it happened that there is a form shown inside of my newsletter. This is even mentioned in the settings page of your plugin, but I didn't think of it in the moment I activated honeyform. Fiddling around with CSS could work but it's fighting symptoms and not the root cause. Thunderbird may flag an html mail with forms as scam / phishing mail. Regardless of using CSS or not.

Possible solution: I guess a list of ids that your plugins checks against would do the job ;)

Thanks again and have a good day!

**Comment by erikyo** [comment]
You are right and we would need a way to control in a more granular way which spam filters are used and on which page.

I was wondering about creating a filter, that is passed an array of spam tests and the post id, something like:

```php
/**
  * Let developers hack the antispam filters
  *
  * @param array|false $enabled_filters the filters enabled in the plugin options, if false the filters are disabled
  * @param int   $post_id the current post id
  */
$enabled_filters = apply_filters( "cf7a_spam_custom_filters", $enabled_filters, $post_id );
```

where `$options` is an array of boolean values like:
`array("fingerprinting"=> 1, "geoip"=> 1, honeypot=> 1, honeyform => 1 ...)`) 

That allows you to configure for a given $post_id what tests are performed, allowing for each page to turn on or off any filter (and not just honeyform). 

What do you think? I like the idea to allow this very fine control over antispam functions!
