### ISSUE TITLE
Request to use PSR-4

### ISSUE THREAD

**Issue by gardenboi** [erikyo/cf7-antispam#49]
Due to recent issues related to unit testing and autoloading @erikyo have come to the conclusion to use [PSR-4](https://www.php-fig.org/psr/psr-4/) coding standard.
This would require us to refactor classes and add namespaces to each file/class implementations. 
The result of this refactoring should guarantee more reliability in terms of program execution, as well let us pass the CI tests with more ease.

**Comment by erikyo** [comment]
closed with #48
