### ISSUE TITLE
Remove warning from CF7

### ISSUE THREAD

**Issue by Zodiac1978** [erikyo/cf7-antispam#63]
CF7 introduced a new validator: unsafe email config in version 5.8.1:
https://contactform7.com/2023/09/28/contact-form-7-581/

See this document for more details:
https://contactform7.com/configuration-errors/unsafe-email-without-protection/

As stated here in this issue this error message will not go away, if Honeypot is used:
https://github.com/rocklobster-in/contact-form-7/issues/1284

But as explained in this doc article it can be disabled:
https://contactform7.com/2023/10/15/disabling-only-specific-error-types-of-config-validator/

Using this code:
```php
add_filter(
    'wpcf7_config_validator_available_error_codes',
    function ( $error_codes, $contact_form ) {
 
        // List error codes to disable here.
        $error_codes_to_disable = array(
            'unsafe_email_without_protection',
        );
 
        $error_codes = array_diff( $error_codes, $error_codes_to_disable );
 
        return $error_codes;
    },
    10, 2
);
```

Maybe you could add this to your plugin.

This could also be a setting or only apply if every form has a honeypot.

**Comment by erikyo** [comment]
Thank you very much, @Zodiac1978!

It would be wonderful (to ensure proper attribution for this suggestion) if you could contribute by adding the provided code to the plugin through a pull request (PR). Would you be open to including the code? I would greatly appreciate it. 
The function needs to be incorporated [here](https://github.com/erikyo/cf7-antispam/blob/34bf100211b134d4a5efbce9593ab2f91ab84599/core/CF7_AntiSpam_Frontend.php#L20) and the hook [here](https://github.com/erikyo/cf7-antispam/blob/34bf100211b134d4a5efbce9593ab2f91ab84599/core/CF7_AntiSpam.php#L260)
Don't worry if it's not perfect; I'll take care of any further adjustments.

Thanks again for your valuable contribution!

**Comment by Zodiac1978** [comment]
I really would like to help, but the composer CLI command doesn't run correctly and there is no working plugin after running the commands. And without any experience with Docker I have no idea how `wp-env start` should run anything. After installing docker it still says `command not found` (maybe just needs more configuration or a docker image I couldn't find yet).

If you can help me to get a running version from the Github main code, I will happily provide the PR.

**Comment by erikyo** [comment]
>  After installing docker it still says command not found (maybe just needs more configuration or a docker image I couldn't find yet).

as I read it sounds like you have not globally installed wp-env, i believe you can solve with:
```
npm -g i @wordpress/env
```

before run the `npm run wp-env command` as described [here](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-env/#quick-tldr-instructions)
